import { Enemy } from '../types.js'

// 60 enemies — 3 per level, levels 1-20
export const ENEMIES: Enemy[] = [
    // ═══ LEVEL 1 ═══ Survivor Camp
    { id: 'starving_wolf', name: '🐺 Starving Wolf', description: 'A wolf driven mad by hunger. Ribs show through patchy fur.', level: 1, stats: { strength: 3, agility: 5, endurance: 2, intelligence: 1, mana: 0 }, gauges: { hp: 35, maxHp: 35, mp: 0, maxMp: 0 }, abilities: [{ name: 'Bite', description: 'Snapping bite', damage: 10, type: 'physical' }, { name: 'Howl', description: 'Chilling howl', damage: 0, type: 'mental', statusEffect: 'fear' }], loot: [{ itemId: 'expired_ration', chance: 0.4, quantity: 1 }], xpReward: 15, currencyReward: 3, type: 'beast', weaknesses: ['fire', 'ice'], resistances: [] },
    { id: 'rabid_dog', name: '🐕 Rabid Dog', description: 'Once a pet, now frothing madness on four legs.', level: 1, stats: { strength: 4, agility: 4, endurance: 2, intelligence: 1, mana: 0 }, gauges: { hp: 40, maxHp: 40, mp: 0, maxMp: 0 }, abilities: [{ name: 'Maul', description: 'Frenzied mauling', damage: 12, type: 'physical' }], loot: [{ itemId: 'expired_ration', chance: 0.3, quantity: 1 }, { itemId: 'bandage', chance: 0.15, quantity: 1 }], xpReward: 18, currencyReward: 4, type: 'beast', weaknesses: ['ice'], resistances: [] },
    { id: 'scavenger_rat', name: '🐀 Giant Scavenger Rat', description: 'A rat the size of a small dog. Carries disease.', level: 1, stats: { strength: 2, agility: 6, endurance: 2, intelligence: 2, mana: 0 }, gauges: { hp: 30, maxHp: 30, mp: 0, maxMp: 0 }, abilities: [{ name: 'Scratch', description: 'Diseased scratch', damage: 8, type: 'physical', statusEffect: 'bleeding' }], loot: [{ itemId: 'expired_ration', chance: 0.35, quantity: 1 }], xpReward: 12, currencyReward: 2, type: 'beast', weaknesses: ['fire', 'poison'], resistances: [] },

    // ═══ LEVEL 2 ═══ Ruined City
    { id: 'corrupted_goblin', name: '👺 Corrupted Goblin', description: 'A goblin twisted by void energy. Glowing eyes.', level: 2, stats: { strength: 4, agility: 4, endurance: 3, intelligence: 2, mana: 5 }, gauges: { hp: 50, maxHp: 50, mp: 15, maxMp: 15 }, abilities: [{ name: 'Rusty Dagger', description: 'Quick dirty stab', damage: 12, type: 'physical' }, { name: 'Void Spark', description: 'Bolt of void energy', damage: 15, type: 'corruption', statusEffect: 'corroded' }], loot: [{ itemId: 'rusty_sword', chance: 0.15, quantity: 1 }, { itemId: 'void_shard', chance: 0.08, quantity: 1 }, { itemId: 'expired_ration', chance: 0.3, quantity: 1 }], xpReward: 30, currencyReward: 8, type: 'spirit', weaknesses: ['holy', 'light'], resistances: ['void', 'shadow'] },
    { id: 'undead_soldier', name: '💀 Undead Soldier', description: 'A soldier who died in the first wave. Now serves a different master.', level: 2, stats: { strength: 6, agility: 2, endurance: 5, intelligence: 1, mana: 0 }, gauges: { hp: 70, maxHp: 70, mp: 0, maxMp: 0 }, abilities: [{ name: 'Heavy Swing', description: 'Slow crushing blow', damage: 16, type: 'physical' }, { name: 'Undying Grip', description: 'Prevents escape', damage: 8, type: 'physical', statusEffect: 'grappled' }], loot: [{ itemId: 'rusty_sword', chance: 0.3, quantity: 1 }, { itemId: 'bandage', chance: 0.25, quantity: 1 }, { itemId: 'broken_amulet', chance: 0.03, quantity: 1 }], xpReward: 40, currencyReward: 12, type: 'undead', weaknesses: ['holy', 'fire'], resistances: ['poison', 'ice'] },
    { id: 'looter_scavenger', name: '🏴‍☠️ Looter Scavenger', description: 'A desperate survivor turned bandit. Armed with a pipe.', level: 2, stats: { strength: 5, agility: 3, endurance: 3, intelligence: 3, mana: 0 }, gauges: { hp: 55, maxHp: 55, mp: 0, maxMp: 0 }, abilities: [{ name: 'Pipe Swing', description: 'Heavy pipe swing', damage: 14, type: 'physical' }, { name: 'Dirty Kick', description: 'Low kick', damage: 10, type: 'physical' }], loot: [{ itemId: 'bandage', chance: 0.4, quantity: 1 }, { itemId: 'mana_potion_small', chance: 0.2, quantity: 1 }], xpReward: 35, currencyReward: 15, type: 'human', weaknesses: ['sword'], resistances: [] },

    // ═══ LEVEL 3 ═══ Dark Forest
    { id: 'shadow_stalker', name: '👤 Shadow Stalker', description: 'Born from pure darkness. It has no face — only a suggestion of one.', level: 3, stats: { strength: 5, agility: 8, endurance: 3, intelligence: 4, mana: 10 }, gauges: { hp: 60, maxHp: 60, mp: 25, maxMp: 25 }, abilities: [{ name: 'Shadow Claw', description: 'Claws through light', damage: 18, type: 'physical' }, { name: 'Engulf', description: 'Suffocating darkness', damage: 22, type: 'mental', statusEffect: 'blind' }], loot: [{ itemId: 'shadow_cloak', chance: 0.05, quantity: 1 }, { itemId: 'void_shard', chance: 0.15, quantity: 2 }, { itemId: 'mana_potion_small', chance: 0.2, quantity: 1 }], xpReward: 55, currencyReward: 15, type: 'abomination', weaknesses: ['light', 'holy', 'fire'], resistances: ['shadow', 'void', 'ice'] },
    { id: 'thorn_beast', name: '🌿 Thorn Beast', description: 'A creature of twisted vines and thorns. Camouflages perfectly.', level: 3, stats: { strength: 6, agility: 5, endurance: 5, intelligence: 3, mana: 8 }, gauges: { hp: 75, maxHp: 75, mp: 15, maxMp: 15 }, abilities: [{ name: 'Vine Whip', description: 'Thorny vine strike', damage: 16, type: 'physical', statusEffect: 'bleeding' }, { name: 'Entangle', description: 'Roots grab target', damage: 10, type: 'physical' }], loot: [{ itemId: 'bandage', chance: 0.3, quantity: 2 }, { itemId: 'mana_potion_small', chance: 0.25, quantity: 1 }], xpReward: 50, currencyReward: 12, type: 'beast', weaknesses: ['fire', 'ice'], resistances: ['nature', 'poison'] },
    { id: 'whispering_wraith', name: '👻 Whispering Wraith', description: 'An echo of someone who died alone. It whispers your fears back at you.', level: 3, stats: { strength: 2, agility: 7, endurance: 3, intelligence: 6, mana: 15 }, gauges: { hp: 50, maxHp: 50, mp: 30, maxMp: 30 }, abilities: [{ name: 'Phantom Touch', description: 'Icy spectral touch', damage: 14, type: 'mental', statusEffect: 'fear' }, { name: 'Scream', description: 'Piercing shriek', damage: 20, type: 'mental' }], loot: [{ itemId: 'memory_shard', chance: 0.25, quantity: 1 }, { itemId: 'void_shard', chance: 0.1, quantity: 1 }], xpReward: 60, currencyReward: 10, type: 'spirit', weaknesses: ['holy', 'light'], resistances: ['physical', 'shadow'] },

    // ═══ LEVEL 4 ═══ Black Market
    { id: 'blood_disciple', name: '🩸 Blood Disciple', description: 'A cultist given to the Blood Order. Veins pulse with borrowed power.', level: 4, stats: { strength: 7, agility: 5, endurance: 6, intelligence: 6, mana: 20 }, gauges: { hp: 95, maxHp: 95, mp: 40, maxMp: 40 }, abilities: [{ name: 'Blood Whip', description: 'Whip of congealed blood', damage: 20, type: 'physical' }, { name: 'Sacrificial Burst', description: 'Sacrifices HP for power', damage: 35, type: 'corruption', statusEffect: 'bleeding' }, { name: 'Life Drain', description: 'Steals life force', damage: 15, type: 'magical' }], loot: [{ itemId: 'blood_crystal', chance: 0.3, quantity: 2 }, { itemId: 'demonic_contract', chance: 0.08, quantity: 1 }, { itemId: 'mana_potion_small', chance: 0.25, quantity: 1 }], xpReward: 85, currencyReward: 30, type: 'human', weaknesses: ['holy', 'light'], resistances: ['blood', 'shadow'] },
    { id: 'enforcer_brute', name: '💪 Enforcer Brute', description: 'Black Market muscle. Paid to break bones, not ask questions.', level: 4, stats: { strength: 10, agility: 3, endurance: 8, intelligence: 2, mana: 0 }, gauges: { hp: 120, maxHp: 120, mp: 0, maxMp: 0 }, abilities: [{ name: 'Crush', description: 'Bone-crushing punch', damage: 25, type: 'physical' }, { name: 'Throw', description: 'Throws debris', damage: 18, type: 'physical' }], loot: [{ itemId: 'bandage', chance: 0.5, quantity: 3 }, { itemId: 'black_market_key', chance: 0.05, quantity: 1 }], xpReward: 75, currencyReward: 35, type: 'human', weaknesses: ['sword', 'ice'], resistances: ['physical'] },
    { id: 'shade_runner', name: '🏃 Shade Runner', description: 'A thief touched by shadow. Moves like smoke in darkness.', level: 4, stats: { strength: 5, agility: 10, endurance: 4, intelligence: 5, mana: 10 }, gauges: { hp: 65, maxHp: 65, mp: 20, maxMp: 20 }, abilities: [{ name: 'Backstab', description: 'Strike from shadows', damage: 22, type: 'physical' }, { name: 'Smoke Bomb', description: 'Vanishes briefly', damage: 10, type: 'physical', statusEffect: 'blind' }], loot: [{ itemId: 'shadow_cloak', chance: 0.08, quantity: 1 }, { itemId: 'black_market_key', chance: 0.1, quantity: 1 }], xpReward: 80, currencyReward: 40, type: 'human', weaknesses: ['light', 'fire'], resistances: ['shadow'] },

    // ═══ LEVEL 5 ═══ Scorched Plains
    { id: 'fallen_knight', name: '🛡️ Fallen Knight', description: 'Once a protector. Now a hollow shell animated by despair.', level: 5, stats: { strength: 10, agility: 4, endurance: 10, intelligence: 3, mana: 5 }, gauges: { hp: 140, maxHp: 140, mp: 20, maxMp: 20 }, abilities: [{ name: "Oathbreaker Strike", description: 'Fueled by broken vows', damage: 28, type: 'physical' }, { name: 'Despair Aura', description: 'Radiating despair', damage: 10, type: 'mental', statusEffect: 'despair' }, { name: 'Shield Bash', description: 'Shattered shield weapon', damage: 18, type: 'physical', statusEffect: 'stunned' }], loot: [{ itemId: 'saints_relic', chance: 0.06, quantity: 1 }, { itemId: 'bandage', chance: 0.4, quantity: 2 }, { itemId: 'memory_shard', chance: 0.15, quantity: 1 }], xpReward: 120, currencyReward: 50, type: 'undead', weaknesses: ['holy', 'light', 'psychic'], resistances: ['poison'] },
    { id: 'ash_wyrmling', name: '🐲 Ash Wyrmling', description: 'A tiny dragon spawn born from volcanic ash. Breathes sparks.', level: 5, stats: { strength: 8, agility: 7, endurance: 7, intelligence: 5, mana: 20 }, gauges: { hp: 110, maxHp: 110, mp: 35, maxMp: 35 }, abilities: [{ name: 'Ash Breath', description: 'Cloud of burning ash', damage: 22, type: 'magical', statusEffect: 'burning' }, { name: 'Tail Whip', description: 'Stinging tail', damage: 16, type: 'physical' }], loot: [{ itemId: 'dragons_scale', chance: 0.2, quantity: 1 }, { itemId: 'void_shard', chance: 0.1, quantity: 1 }], xpReward: 110, currencyReward: 45, type: 'dragon', weaknesses: ['ice', 'holy'], resistances: ['fire'] },
    { id: 'cinder_elemental', name: '🔥 Cinder Elemental', description: 'Living fire barely held together by will. Burns everything.', level: 5, stats: { strength: 4, agility: 6, endurance: 5, intelligence: 5, mana: 25 }, gauges: { hp: 85, maxHp: 85, mp: 40, maxMp: 40 }, abilities: [{ name: 'Fireball', description: 'Blazing sphere', damage: 25, type: 'magical', statusEffect: 'burning' }, { name: 'Heat Wave', description: 'Scorching wave', damage: 18, type: 'magical' }], loot: [{ itemId: 'mana_potion_small', chance: 0.4, quantity: 2 }, { itemId: 'phoenix_feather', chance: 0.02, quantity: 1 }], xpReward: 105, currencyReward: 35, type: 'spirit', weaknesses: ['ice', 'water'], resistances: ['fire', 'physical'] },

    // ═══ LEVEL 6 ═══ Cathedral Ruins
    { id: 'hollow_saint', name: '😇 Hollow Saint', description: 'A saint whose faith curdled into something hungry.', level: 6, stats: { strength: 7, agility: 6, endurance: 8, intelligence: 10, mana: 30 }, gauges: { hp: 130, maxHp: 130, mp: 50, maxMp: 50 }, abilities: [{ name: 'Hollow Prayer', description: 'Twisted holy energy', damage: 25, type: 'magical' }, { name: 'Martyr Touch', description: 'Burns with corrupted light', damage: 30, type: 'corruption', statusEffect: 'corroded' }], loot: [{ itemId: 'saints_relic', chance: 0.2, quantity: 2 }, { itemId: 'holy_water', chance: 0.35, quantity: 1 }], xpReward: 160, currencyReward: 60, type: 'undead', weaknesses: ['void', 'shadow'], resistances: ['holy', 'light'] },
    { id: 'bell_gargoyle', name: '🦇 Bell Gargoyle', description: 'Stone guardian of the bell tower. Still rings for the dead.', level: 6, stats: { strength: 12, agility: 5, endurance: 10, intelligence: 3, mana: 10 }, gauges: { hp: 180, maxHp: 180, mp: 20, maxMp: 20 }, abilities: [{ name: 'Stone Slam', description: 'Massive stone smash', damage: 30, type: 'physical' }, { name: 'Bell Toll', description: 'Sonic shockwave', damage: 20, type: 'mental', statusEffect: 'stunned' }], loot: [{ itemId: 'tower_key_fragment', chance: 0.1, quantity: 1 }, { itemId: 'bandage', chance: 0.5, quantity: 3 }], xpReward: 150, currencyReward: 70, type: 'abomination', weaknesses: ['thunder', 'ice'], resistances: ['physical', 'fire'] },
    { id: 'penitent_ghost', name: '👼 Penitent Ghost', description: 'A worshipper who died begging. Still begs — but for company in death.', level: 6, stats: { strength: 3, agility: 8, endurance: 5, intelligence: 8, mana: 25 }, gauges: { hp: 95, maxHp: 95, mp: 45, maxMp: 45 }, abilities: [{ name: 'Wail', description: 'Mournful cry', damage: 22, type: 'mental', statusEffect: 'fear' }, { name: 'Soul Grab', description: 'Tries to pull you under', damage: 28, type: 'magical' }], loot: [{ itemId: 'memory_shard', chance: 0.3, quantity: 2 }, { itemId: 'holy_water', chance: 0.2, quantity: 1 }], xpReward: 140, currencyReward: 55, type: 'spirit', weaknesses: ['holy'], resistances: ['physical', 'shadow'] },

    // ═══ LEVEL 7 ═══ Frozen Wastes
    { id: 'frost_troll', name: '🧊 Frost Troll', description: 'A massive troll crusted in ice. Lived here before the System.', level: 7, stats: { strength: 14, agility: 3, endurance: 12, intelligence: 3, mana: 10 }, gauges: { hp: 220, maxHp: 220, mp: 15, maxMp: 15 }, abilities: [{ name: 'Ice Club', description: 'Frozen club smash', damage: 32, type: 'physical' }, { name: 'Frost Breath', description: 'Freezing gust', damage: 20, type: 'magical', statusEffect: 'stunned' }], loot: [{ itemId: 'dragons_scale', chance: 0.15, quantity: 2 }, { itemId: 'bandage', chance: 0.5, quantity: 4 }], xpReward: 200, currencyReward: 85, type: 'beast', weaknesses: ['fire', 'thunder'], resistances: ['ice', 'physical'] },
    { id: 'ice_wraith', name: '❄️ Ice Wraith', description: 'A spirit trapped in eternal cold. Feeds on body heat.', level: 7, stats: { strength: 4, agility: 9, endurance: 6, intelligence: 9, mana: 30 }, gauges: { hp: 105, maxHp: 105, mp: 55, maxMp: 55 }, abilities: [{ name: 'Freeze', description: 'Flash-freezes air', damage: 24, type: 'magical', statusEffect: 'stunned' }, { name: 'Icicle Storm', description: 'Raining ice shards', damage: 28, type: 'magical' }], loot: [{ itemId: 'void_shard', chance: 0.25, quantity: 3 }, { itemId: 'mana_potion_small', chance: 0.4, quantity: 2 }], xpReward: 190, currencyReward: 75, type: 'spirit', weaknesses: ['fire', 'thunder'], resistances: ['ice', 'physical'] },
    { id: 'yeti_cub', name: '🐻‍❄️ Yeti Cub', description: 'A young yeti separated from its pack. Desperate and dangerous.', level: 7, stats: { strength: 10, agility: 6, endurance: 10, intelligence: 4, mana: 5 }, gauges: { hp: 170, maxHp: 170, mp: 10, maxMp: 10 }, abilities: [{ name: 'Claw Swipe', description: 'Massive claw rake', damage: 26, type: 'physical', statusEffect: 'bleeding' }, { name: 'Frost Roar', description: 'Chilling roar', damage: 15, type: 'mental' }], loot: [{ itemId: 'bandage', chance: 0.6, quantity: 3 }, { itemId: 'dragons_scale', chance: 0.1, quantity: 1 }], xpReward: 180, currencyReward: 80, type: 'beast', weaknesses: ['fire'], resistances: ['ice'] },

    // ═══ LEVEL 8 ═══ Tower Gate
    { id: 'young_drake', name: '🐉 Young Drake', description: 'A young dragon, barely a century old. Even young, it is terrifying.', level: 8, stats: { strength: 15, agility: 8, endurance: 12, intelligence: 10, mana: 30 }, gauges: { hp: 250, maxHp: 250, mp: 60, maxMp: 60 }, abilities: [{ name: 'Fire Breath', description: 'Searing flame cone', damage: 40, type: 'magical', statusEffect: 'burning' }, { name: 'Tail Sweep', description: 'Crushing tail', damage: 30, type: 'physical' }, { name: 'Dragon Roar', description: 'Soul-shaking roar', damage: 15, type: 'mental', statusEffect: 'fear' }], loot: [{ itemId: 'dragons_scale', chance: 0.6, quantity: 2 }, { itemId: 'phoenix_feather', chance: 0.03, quantity: 1 }, { itemId: 'tower_key_fragment', chance: 0.08, quantity: 1 }], xpReward: 350, currencyReward: 200, type: 'dragon', weaknesses: ['ice'], resistances: ['fire', 'poison', 'blood'] },
    { id: 'gate_sentinel', name: '🗿 Gate Sentinel', description: 'An animated stone guardian. Built to test — and destroy — climbers.', level: 8, stats: { strength: 16, agility: 4, endurance: 14, intelligence: 2, mana: 20 }, gauges: { hp: 300, maxHp: 300, mp: 30, maxMp: 30 }, abilities: [{ name: 'Stone Fist', description: 'Massive punch', damage: 35, type: 'physical' }, { name: 'Laser Eye', description: 'Arcane beam', damage: 30, type: 'magical' }], loot: [{ itemId: 'tower_key_fragment', chance: 0.2, quantity: 2 }, { itemId: 'void_shard', chance: 0.4, quantity: 3 }], xpReward: 320, currencyReward: 180, type: 'abomination', weaknesses: ['thunder', 'ice'], resistances: ['physical', 'fire', 'poison'] },
    { id: 'climber_remnant', name: '🧟 Climber Remnant', description: 'A climber who failed. Now guards the gate for eternity.', level: 8, stats: { strength: 11, agility: 7, endurance: 9, intelligence: 6, mana: 15 }, gauges: { hp: 190, maxHp: 190, mp: 25, maxMp: 25 }, abilities: [{ name: 'Desperate Strike', description: 'All-or-nothing slash', damage: 28, type: 'physical' }, { name: 'Tower Curse', description: 'Curses your climb', damage: 20, type: 'corruption' }], loot: [{ itemId: 'memory_shard', chance: 0.4, quantity: 3 }, { itemId: 'phoenix_feather', chance: 0.02, quantity: 1 }], xpReward: 300, currencyReward: 190, type: 'undead', weaknesses: ['holy', 'light'], resistances: ['shadow'] },

    // ═══ LEVEL 9 ═══ Void Rift
    { id: 'void_herald', name: '👁️ Void Herald', description: 'A messenger from the void. Its form shifts as you look.', level: 9, stats: { strength: 12, agility: 15, endurance: 10, intelligence: 20, mana: 60 }, gauges: { hp: 300, maxHp: 300, mp: 100, maxMp: 100 }, abilities: [{ name: 'Void Lance', description: 'Pure void spear', damage: 45, type: 'corruption', statusEffect: 'corroded' }, { name: 'Mind Shatter', description: 'Sanity attack', damage: 35, type: 'mental', statusEffect: 'madness' }, { name: 'Reality Tear', description: 'Rips reality', damage: 60, type: 'corruption' }], loot: [{ itemId: 'void_shard', chance: 0.8, quantity: 5 }, { itemId: 'memory_shard', chance: 0.4, quantity: 3 }, { itemId: 'tower_key_fragment', chance: 0.15, quantity: 2 }], xpReward: 600, currencyReward: 500, type: 'abomination', weaknesses: ['holy', 'light'], resistances: ['void', 'shadow', 'psychic', 'physical'] },
    { id: 'reality_warp', name: '🌀 Reality Warp', description: 'A crack in space that fights like a living thing.', level: 9, stats: { strength: 8, agility: 12, endurance: 15, intelligence: 18, mana: 70 }, gauges: { hp: 280, maxHp: 280, mp: 120, maxMp: 120 }, abilities: [{ name: 'Dimensional Slice', description: 'Cuts through space', damage: 40, type: 'corruption' }, { name: 'Paradox', description: 'Time loops damage', damage: 35, type: 'magical' }], loot: [{ itemId: 'void_shard', chance: 0.7, quantity: 6 }, { itemId: 'memory_shard', chance: 0.5, quantity: 4 }], xpReward: 550, currencyReward: 450, type: 'abomination', weaknesses: ['holy'], resistances: ['physical', 'mental', 'void'] },
    { id: 'void_spawn', name: '🕳️ Void Spawn', description: 'An infant thing from the void. Hungry. Growing.', level: 9, stats: { strength: 10, agility: 14, endurance: 12, intelligence: 15, mana: 55 }, gauges: { hp: 260, maxHp: 260, mp: 90, maxMp: 90 }, abilities: [{ name: 'Consume', description: 'Tries to devour', damage: 38, type: 'corruption' }, { name: 'Void Scream', description: 'Silent scream', damage: 30, type: 'mental' }], loot: [{ itemId: 'void_shard', chance: 0.6, quantity: 4 }, { itemId: 'demonic_contract', chance: 0.05, quantity: 1 }], xpReward: 520, currencyReward: 480, type: 'abomination', weaknesses: ['light', 'holy'], resistances: ['void', 'shadow'] },

    // ═══ LEVEL 10 ═══ Abyssal Depths
    { id: 'abyssal_horror', name: '👾 Abyssal Horror', description: 'Something that should not exist. Your mind struggles to comprehend.', level: 10, stats: { strength: 18, agility: 12, endurance: 16, intelligence: 22, mana: 80 }, gauges: { hp: 400, maxHp: 400, mp: 150, maxMp: 150 }, abilities: [{ name: 'Unmake', description: 'Tries to erase you', damage: 50, type: 'corruption' }, { name: 'Madness Gaze', description: 'Drives mind to breaking', damage: 40, type: 'mental', statusEffect: 'madness' }, { name: 'Tentacle Strike', description: 'Unseen appendages', damage: 45, type: 'physical' }], loot: [{ itemId: 'void_shard', chance: 0.9, quantity: 8 }, { itemId: 'phoenix_feather', chance: 0.05, quantity: 1 }, { itemId: 'demonic_contract', chance: 0.1, quantity: 1 }], xpReward: 800, currencyReward: 700, type: 'demon', weaknesses: ['holy', 'light'], resistances: ['void', 'shadow', 'mental'] },
    { id: 'fallen_constellation', name: '⭐ Fallen Constellation', description: 'A dead star that fell here eons ago. It still remembers what it was.', level: 10, stats: { strength: 14, agility: 10, endurance: 18, intelligence: 25, mana: 100 }, gauges: { hp: 380, maxHp: 380, mp: 180, maxMp: 180 }, abilities: [{ name: 'Starfall', description: 'Fragment of dying star', damage: 55, type: 'magical', statusEffect: 'burning' }, { name: 'Gravity Well', description: 'Crushing gravity', damage: 40, type: 'physical' }], loot: [{ itemId: 'memory_shard', chance: 0.6, quantity: 5 }, { itemId: 'saints_relic', chance: 0.15, quantity: 2 }, { itemId: 'tower_key_fragment', chance: 0.2, quantity: 3 }], xpReward: 750, currencyReward: 650, type: 'abomination', weaknesses: ['void', 'shadow'], resistances: ['light', 'holy', 'fire'] },
    { id: 'deep_one', name: '🐙 Deep One', description: 'Ancient and patient. It has waited in the dark for longer than humanity has existed.', level: 10, stats: { strength: 16, agility: 8, endurance: 20, intelligence: 20, mana: 70 }, gauges: { hp: 450, maxHp: 450, mp: 130, maxMp: 130 }, abilities: [{ name: 'Crushing Depths', description: 'Pressure of the abyss', damage: 48, type: 'physical' }, { name: 'Ancient Whispers', description: 'Eons of madness', damage: 35, type: 'mental', statusEffect: 'madness' }], loot: [{ itemId: 'dragons_scale', chance: 0.5, quantity: 4 }, { itemId: 'phoenix_feather', chance: 0.08, quantity: 1 }, { itemId: 'demonic_contract', chance: 0.12, quantity: 1 }], xpReward: 780, currencyReward: 680, type: 'demon', weaknesses: ['thunder', 'holy'], resistances: ['void', 'ice', 'poison'] },

    // ═══ LEVEL 11 ═══
    { id: 'crystal_golem', name: '💎 Crystal Golem', description: 'A golem formed from crystallized void energy. Beautiful and lethal.', level: 11, stats: { strength: 18, agility: 6, endurance: 18, intelligence: 8, mana: 40 }, gauges: { hp: 420, maxHp: 420, mp: 60, maxMp: 60 }, abilities: [{ name: 'Crystal Shard', description: 'Shrapnel burst', damage: 42, type: 'physical' }, { name: 'Prism Beam', description: 'Refracted energy', damage: 50, type: 'magical' }], loot: [{ itemId: 'void_shard', chance: 0.8, quantity: 6 }, { itemId: 'dragons_scale', chance: 0.3, quantity: 3 }], xpReward: 650, currencyReward: 400, type: 'abomination', weaknesses: ['thunder'], resistances: ['physical', 'magical'] },
    { id: 'spectral_knight', name: '⚔️ Spectral Knight', description: 'A knight who swore an oath beyond death. Still serves.', level: 11, stats: { strength: 16, agility: 10, endurance: 14, intelligence: 10, mana: 30 }, gauges: { hp: 350, maxHp: 350, mp: 50, maxMp: 50 }, abilities: [{ name: 'Spectral Slash', description: 'Blade through dimensions', damage: 38, type: 'physical' }, { name: 'Oathbind', description: 'Binds your soul', damage: 30, type: 'magical' }], loot: [{ itemId: 'cursed_blade_hunger', chance: 0.05, quantity: 1 }, { itemId: 'memory_shard', chance: 0.5, quantity: 3 }], xpReward: 620, currencyReward: 420, type: 'undead', weaknesses: ['holy'], resistances: ['physical', 'shadow'] },
    { id: 'venom_hydra_spawn', name: '🐍 Venom Hydra Spawn', description: 'Two-headed spawn of the great hydra. Venom drips from both mouths.', level: 11, stats: { strength: 14, agility: 10, endurance: 14, intelligence: 6, mana: 20 }, gauges: { hp: 380, maxHp: 380, mp: 30, maxMp: 30 }, abilities: [{ name: 'Dual Bite', description: 'Two heads strike', damage: 36, type: 'physical', statusEffect: 'bleeding' }, { name: 'Venom Spray', description: 'Toxic mist', damage: 30, type: 'magical', statusEffect: 'bleeding' }], loot: [{ itemId: 'bandage', chance: 0.7, quantity: 4 }, { itemId: 'dragons_scale', chance: 0.2, quantity: 2 }], xpReward: 640, currencyReward: 410, type: 'beast', weaknesses: ['fire', 'ice'], resistances: ['poison'] },

    // ═══ LEVEL 12 ═══
    { id: 'doom_knight', name: '🖤 Doom Knight', description: 'Armor filled with pure hatred. Its sword remembers every life it took.', level: 12, stats: { strength: 20, agility: 12, endurance: 16, intelligence: 8, mana: 30 }, gauges: { hp: 500, maxHp: 500, mp: 45, maxMp: 45 }, abilities: [{ name: 'Doom Cleave', description: 'Obliterating slash', damage: 48, type: 'physical' }, { name: 'Hate Aura', description: 'Crushing hatred', damage: 30, type: 'mental' }], loot: [{ itemId: 'cursed_blade_hunger', chance: 0.08, quantity: 1 }, { itemId: 'saints_relic', chance: 0.15, quantity: 2 }], xpReward: 750, currencyReward: 550, type: 'undead', weaknesses: ['holy', 'light'], resistances: ['physical', 'shadow', 'mental'] },
    { id: 'phoenix_hatchling', name: '🐦‍🔥 Phoenix Hatchling', description: 'A baby phoenix. Even newborns burn with eternal fire.', level: 12, stats: { strength: 8, agility: 14, endurance: 10, intelligence: 14, mana: 60 }, gauges: { hp: 280, maxHp: 280, mp: 90, maxMp: 90 }, abilities: [{ name: 'Fire Wing', description: 'Blazing wing sweep', damage: 42, type: 'magical', statusEffect: 'burning' }, { name: 'Rebirth Flame', description: 'Heals itself', damage: 0, type: 'magical' }], loot: [{ itemId: 'phoenix_feather', chance: 0.15, quantity: 1 }, { itemId: 'dragons_scale', chance: 0.3, quantity: 2 }], xpReward: 720, currencyReward: 520, type: 'spirit', weaknesses: ['ice'], resistances: ['fire', 'holy'] },
    { id: 'shadow_dragon_whelp', name: '🐉‍⬛ Shadow Dragon Whelp', description: 'A dragon born in darkness. Breathes pure shadow.', level: 12, stats: { strength: 16, agility: 14, endurance: 12, intelligence: 12, mana: 45 }, gauges: { hp: 400, maxHp: 400, mp: 70, maxMp: 70 }, abilities: [{ name: 'Shadow Breath', description: 'Breath of darkness', damage: 44, type: 'corruption' }, { name: 'Dark Claw', description: 'Shadow-reinforced claws', damage: 36, type: 'physical' }], loot: [{ itemId: 'dragons_scale', chance: 0.5, quantity: 3 }, { itemId: 'shadow_cloak', chance: 0.1, quantity: 1 }], xpReward: 730, currencyReward: 540, type: 'dragon', weaknesses: ['light', 'holy'], resistances: ['shadow', 'void'] },

    // ═══ LEVEL 13 ═══
    { id: 'lich_apprentice', name: '🧙‍♂️ Lich Apprentice', description: 'A mage who failed at immortality. Still learning.', level: 13, stats: { strength: 6, agility: 8, endurance: 12, intelligence: 22, mana: 80 }, gauges: { hp: 320, maxHp: 320, mp: 130, maxMp: 130 }, abilities: [{ name: 'Soul Drain', description: 'Steals life essence', damage: 40, type: 'magical' }, { name: 'Death Bolt', description: 'Bolt of pure death', damage: 50, type: 'corruption' }], loot: [{ itemId: 'memory_shard', chance: 0.6, quantity: 4 }, { itemId: 'demonic_contract', chance: 0.1, quantity: 1 }], xpReward: 800, currencyReward: 600, type: 'undead', weaknesses: ['holy', 'fire'], resistances: ['shadow', 'poison', 'ice'] },
    { id: 'war_golem', name: '🦾 War Golem', description: 'Ancient war machine reactivated by the System. Seeks combat.', level: 13, stats: { strength: 22, agility: 5, endurance: 20, intelligence: 3, mana: 20 }, gauges: { hp: 600, maxHp: 600, mp: 25, maxMp: 25 }, abilities: [{ name: 'Rocket Punch', description: 'Launches its fist', damage: 52, type: 'physical' }, { name: 'Overcharge', description: 'Electric discharge', damage: 45, type: 'magical' }], loot: [{ itemId: 'void_shard', chance: 0.5, quantity: 5 }, { itemId: 'bandage', chance: 0.8, quantity: 5 }], xpReward: 780, currencyReward: 580, type: 'abomination', weaknesses: ['thunder', 'ice'], resistances: ['physical', 'fire'] },
    { id: 'banshee_queen', name: '👸 Banshee Queen', description: 'A queen who watched her kingdom fall. Her scream still echoes.', level: 13, stats: { strength: 4, agility: 12, endurance: 10, intelligence: 18, mana: 55 }, gauges: { hp: 280, maxHp: 280, mp: 90, maxMp: 90 }, abilities: [{ name: 'Death Scream', description: 'Shattering wail', damage: 46, type: 'mental' }, { name: 'Spectral Claw', description: 'Ethereal swipe', damage: 35, type: 'magical' }], loot: [{ itemId: 'mask_of_madness', chance: 0.05, quantity: 1 }, { itemId: 'memory_shard', chance: 0.5, quantity: 4 }], xpReward: 760, currencyReward: 560, type: 'spirit', weaknesses: ['holy'], resistances: ['physical', 'mental'] },

    // ═══ LEVEL 14 ═══
    { id: 'demon_commander', name: '👹 Demon Commander', description: 'A general of the abyssal legion. Commands lesser demons.', level: 14, stats: { strength: 20, agility: 14, endurance: 16, intelligence: 16, mana: 70 }, gauges: { hp: 520, maxHp: 520, mp: 110, maxMp: 110 }, abilities: [{ name: 'Hellfire', description: 'Green flames', damage: 55, type: 'magical', statusEffect: 'burning' }, { name: 'Command Strike', description: 'Orders minion to strike', damage: 40, type: 'physical' }], loot: [{ itemId: 'demonic_contract', chance: 0.15, quantity: 1 }, { itemId: 'blood_crystal', chance: 0.4, quantity: 4 }], xpReward: 900, currencyReward: 750, type: 'demon', weaknesses: ['holy', 'light'], resistances: ['fire', 'shadow'] },
    { id: 'titan_skeleton', name: '🦴 Titan Skeleton', description: 'The bones of something impossibly large. It still moves.', level: 14, stats: { strength: 24, agility: 3, endurance: 22, intelligence: 2, mana: 0 }, gauges: { hp: 700, maxHp: 700, mp: 0, maxMp: 0 }, abilities: [{ name: 'Stomp', description: 'Shakes the ground', damage: 50, type: 'physical' }, { name: 'Bone Throw', description: 'Hurls its own bones', damage: 42, type: 'physical' }], loot: [{ itemId: 'dragons_scale', chance: 0.5, quantity: 4 }, { itemId: 'saints_relic', chance: 0.2, quantity: 3 }], xpReward: 850, currencyReward: 700, type: 'undead', weaknesses: ['holy', 'thunder'], resistances: ['physical', 'poison'] },
    { id: 'mind_flayer_young', name: '🧠 Mind Flayer (Young)', description: 'A young creature that feeds on thoughts. Its tentacles probe for your fears.', level: 14, stats: { strength: 8, agility: 12, endurance: 10, intelligence: 24, mana: 90 }, gauges: { hp: 300, maxHp: 300, mp: 140, maxMp: 140 }, abilities: [{ name: 'Mind Blast', description: 'Psychic explosion', damage: 50, type: 'mental', statusEffect: 'madness' }, { name: 'Brain Drain', description: 'Feeds on intellect', damage: 45, type: 'magical' }], loot: [{ itemId: 'memory_shard', chance: 0.7, quantity: 5 }, { itemId: 'mask_of_madness', chance: 0.08, quantity: 1 }], xpReward: 880, currencyReward: 720, type: 'abomination', weaknesses: ['psychic', 'thunder'], resistances: ['mental', 'magical'] },

    // ═══ LEVEL 15 ═══
    { id: 'ancient_lich', name: '☠️ Ancient Lich', description: 'A lich who has lived centuries. Death is merely a suggestion to it.', level: 15, stats: { strength: 8, agility: 10, endurance: 14, intelligence: 26, mana: 100 }, gauges: { hp: 380, maxHp: 380, mp: 160, maxMp: 160 }, abilities: [{ name: 'Finger of Death', description: 'Instant death touch', damage: 60, type: 'corruption' }, { name: 'Soul Cage', description: 'Traps your soul', damage: 48, type: 'magical' }], loot: [{ itemId: 'phoenix_feather', chance: 0.1, quantity: 1 }, { itemId: 'demonic_contract', chance: 0.2, quantity: 1 }], xpReward: 1000, currencyReward: 850, type: 'undead', weaknesses: ['holy', 'light'], resistances: ['shadow', 'poison', 'ice', 'mental'] },
    { id: 'behemoth', name: '🦏 Behemoth', description: 'A living mountain of muscle and rage. The ground shakes with every step.', level: 15, stats: { strength: 26, agility: 4, endurance: 24, intelligence: 3, mana: 10 }, gauges: { hp: 800, maxHp: 800, mp: 15, maxMp: 15 }, abilities: [{ name: 'Charge', description: 'Full-body ram', damage: 58, type: 'physical' }, { name: 'Earthquake', description: 'Shatters the ground', damage: 45, type: 'physical' }], loot: [{ itemId: 'dragons_scale', chance: 0.6, quantity: 5 }, { itemId: 'bandage', chance: 0.9, quantity: 6 }], xpReward: 950, currencyReward: 800, type: 'beast', weaknesses: ['ice', 'poison'], resistances: ['physical', 'fire'] },
    { id: 'celestial_warden', name: '✨ Celestial Warden', description: 'A being of pure light tasked with guarding something lost. It judges you silently.', level: 15, stats: { strength: 14, agility: 16, endurance: 14, intelligence: 20, mana: 80 }, gauges: { hp: 450, maxHp: 450, mp: 130, maxMp: 130 }, abilities: [{ name: 'Light Spear', description: 'Spear of judgment', damage: 52, type: 'magical' }, { name: 'Blinding Flash', description: 'Overwhelming light', damage: 40, type: 'magical', statusEffect: 'blind' }], loot: [{ itemId: 'saints_relic', chance: 0.3, quantity: 3 }, { itemId: 'phoenix_feather', chance: 0.08, quantity: 1 }], xpReward: 980, currencyReward: 820, type: 'spirit', weaknesses: ['void', 'shadow'], resistances: ['holy', 'light'] },

    // ═══ LEVEL 16 ═══
    { id: 'abyss_lord', name: '😈 Abyss Lord', description: 'A demon prince of the deepest abyss. Your soul tingles with corruption near it.', level: 16, stats: { strength: 22, agility: 16, endurance: 18, intelligence: 22, mana: 100 }, gauges: { hp: 600, maxHp: 600, mp: 150, maxMp: 150 }, abilities: [{ name: 'Abyssal Flame', description: 'Black fire', damage: 65, type: 'corruption' }, { name: 'Demon Command', description: 'Summons lesser demons', damage: 50, type: 'magical' }], loot: [{ itemId: 'demonic_contract', chance: 0.25, quantity: 2 }, { itemId: 'blood_crystal', chance: 0.6, quantity: 6 }], xpReward: 1150, currencyReward: 1000, type: 'demon', weaknesses: ['holy'], resistances: ['fire', 'shadow', 'void'] },
    { id: 'dragon_elder', name: '🐲 Dragon Elder', description: 'A dragon on the verge of becoming ancient. Its eyes hold millennia.', level: 16, stats: { strength: 22, agility: 14, endurance: 20, intelligence: 18, mana: 90 }, gauges: { hp: 650, maxHp: 650, mp: 140, maxMp: 140 }, abilities: [{ name: 'Inferno', description: 'Sea of fire', damage: 62, type: 'magical', statusEffect: 'burning' }, { name: 'Crushing Maw', description: 'Bites with ancient force', damage: 55, type: 'physical' }], loot: [{ itemId: 'dragons_scale', chance: 0.8, quantity: 6 }, { itemId: 'phoenix_feather', chance: 0.12, quantity: 1 }], xpReward: 1100, currencyReward: 950, type: 'dragon', weaknesses: ['ice', 'holy'], resistances: ['fire', 'physical'] },
    { id: 'void_colossus', name: '🌑 Void Colossus', description: 'A giant forged from pure void. It erases what it touches.', level: 16, stats: { strength: 24, agility: 8, endurance: 22, intelligence: 14, mana: 60 }, gauges: { hp: 700, maxHp: 700, mp: 90, maxMp: 90 }, abilities: [{ name: 'Void Slam', description: 'Crushing void fist', damage: 58, type: 'corruption' }, { name: 'Erase', description: 'Attempts to unmake', damage: 70, type: 'corruption' }], loot: [{ itemId: 'void_shard', chance: 0.9, quantity: 10 }, { itemId: 'tower_key_fragment', chance: 0.3, quantity: 4 }], xpReward: 1120, currencyReward: 980, type: 'abomination', weaknesses: ['light', 'holy'], resistances: ['physical', 'void', 'shadow'] },

    // ═══ LEVEL 17 ═══
    { id: 'seraphim_fallen', name: '🪽 Fallen Seraphim', description: 'An angel that fell with the constellations. Its broken halo still glows faintly.', level: 17, stats: { strength: 18, agility: 18, endurance: 16, intelligence: 24, mana: 120 }, gauges: { hp: 550, maxHp: 550, mp: 180, maxMp: 180 }, abilities: [{ name: 'Fallen Light', description: 'Corrupted holy flame', damage: 60, type: 'magical' }, { name: 'Judgment', description: 'Passes judgment', damage: 70, type: 'mental' }], loot: [{ itemId: 'saints_relic', chance: 0.4, quantity: 4 }, { itemId: 'phoenix_feather', chance: 0.15, quantity: 1 }], xpReward: 1250, currencyReward: 1100, type: 'spirit', weaknesses: ['void'], resistances: ['holy', 'light', 'fire'] },
    { id: 'hydra', name: '🐉 Hydra', description: 'The legendary multi-headed serpent. Cut one head, two grow back.', level: 17, stats: { strength: 22, agility: 14, endurance: 20, intelligence: 10, mana: 50 }, gauges: { hp: 700, maxHp: 700, mp: 80, maxMp: 80 }, abilities: [{ name: 'Multi-Bite', description: 'All heads strike', damage: 58, type: 'physical' }, { name: 'Acid Spit', description: 'Burning acid', damage: 52, type: 'magical', statusEffect: 'burning' }], loot: [{ itemId: 'dragons_scale', chance: 0.7, quantity: 5 }, { itemId: 'blood_crystal', chance: 0.5, quantity: 5 }], xpReward: 1200, currencyReward: 1050, type: 'beast', weaknesses: ['fire', 'ice'], resistances: ['poison', 'physical'] },
    { id: 'time_wraith', name: '⏳ Time Wraith', description: 'A ghost that exists slightly out of phase with time. Your attacks sometimes miss.', level: 17, stats: { strength: 6, agility: 20, endurance: 12, intelligence: 20, mana: 80 }, gauges: { hp: 380, maxHp: 380, mp: 130, maxMp: 130 }, abilities: [{ name: 'Temporal Slice', description: 'Cuts through moments', damage: 56, type: 'magical' }, { name: 'Age', description: 'Ages you momentarily', damage: 48, type: 'magical' }], loot: [{ itemId: 'memory_shard', chance: 0.8, quantity: 6 }, { itemId: 'tower_key_fragment', chance: 0.2, quantity: 3 }], xpReward: 1220, currencyReward: 1080, type: 'spirit', weaknesses: ['void', 'psychic'], resistances: ['physical'] },

    // ═══ LEVEL 18 ═══
    { id: 'dragon_ancient', name: '🔥 Ancient Dragon', description: 'A dragon of impossible age. Its scales have seen civilizations rise and fall.', level: 18, stats: { strength: 26, agility: 16, endurance: 24, intelligence: 22, mana: 100 }, gauges: { hp: 800, maxHp: 800, mp: 160, maxMp: 160 }, abilities: [{ name: 'Cataclysm Breath', description: 'World-ending fire', damage: 75, type: 'magical', statusEffect: 'burning' }, { name: 'Dragon Roar', description: 'Ancient roar', damage: 55, type: 'mental', statusEffect: 'fear' }], loot: [{ itemId: 'dragons_scale', chance: 0.9, quantity: 8 }, { itemId: 'phoenix_feather', chance: 0.2, quantity: 2 }], xpReward: 1500, currencyReward: 1400, type: 'dragon', weaknesses: ['ice'], resistances: ['fire', 'physical', 'poison'] },
    { id: 'world_eater', name: '🌍 World Eater', description: 'A creature that consumes worlds. This one is still young — small enough to fight.', level: 18, stats: { strength: 28, agility: 10, endurance: 26, intelligence: 14, mana: 80 }, gauges: { hp: 900, maxHp: 900, mp: 100, maxMp: 100 }, abilities: [{ name: 'Consume', description: 'Devours matter', damage: 72, type: 'corruption' }, { name: 'Gravity Crush', description: 'Increases gravity', damage: 60, type: 'physical' }], loot: [{ itemId: 'void_shard', chance: 0.9, quantity: 12 }, { itemId: 'demonic_contract', chance: 0.2, quantity: 2 }], xpReward: 1450, currencyReward: 1350, type: 'demon', weaknesses: ['light', 'holy'], resistances: ['void', 'physical'] },
    { id: 'death_knight', name: '💀 Death Knight', description: 'A legendary warrior who conquered death. Now serves it.', level: 18, stats: { strength: 24, agility: 16, endurance: 20, intelligence: 14, mana: 60 }, gauges: { hp: 750, maxHp: 750, mp: 90, maxMp: 90 }, abilities: [{ name: 'Death Strike', description: 'Mortal end', damage: 68, type: 'physical' }, { name: 'Soul Rend', description: 'Tears at soul', damage: 58, type: 'magical' }], loot: [{ itemId: 'cursed_blade_hunger', chance: 0.15, quantity: 1 }, { itemId: 'saints_relic', chance: 0.4, quantity: 4 }], xpReward: 1480, currencyReward: 1380, type: 'undead', weaknesses: ['holy', 'light'], resistances: ['physical', 'shadow'] },

    // ═══ LEVEL 19 ═══
    { id: 'constellation', name: '🌠 Living Constellation', description: 'A star that became alive. Its light burns through reality.', level: 19, stats: { strength: 14, agility: 18, endurance: 18, intelligence: 28, mana: 150 }, gauges: { hp: 600, maxHp: 600, mp: 220, maxMp: 220 }, abilities: [{ name: 'Nova', description: 'Exploding star', damage: 80, type: 'magical', statusEffect: 'burning' }, { name: 'Cosmic Ray', description: 'Pierces dimensions', damage: 72, type: 'magical' }], loot: [{ itemId: 'memory_shard', chance: 0.9, quantity: 8 }, { itemId: 'phoenix_feather', chance: 0.25, quantity: 2 }], xpReward: 1800, currencyReward: 1600, type: 'abomination', weaknesses: ['void'], resistances: ['light', 'fire', 'physical'] },
    { id: 'primordial_ooze', name: '🟢 Primordial Ooze', description: 'The first life. The last life. It absorbs everything.', level: 19, stats: { strength: 20, agility: 8, endurance: 28, intelligence: 10, mana: 40 }, gauges: { hp: 900, maxHp: 900, mp: 60, maxMp: 60 }, abilities: [{ name: 'Absorb', description: 'Absorbs your strength', damage: 65, type: 'physical' }, { name: 'Divide', description: 'Splits into copies', damage: 55, type: 'physical' }], loot: [{ itemId: 'void_shard', chance: 0.8, quantity: 10 }, { itemId: 'dragons_scale', chance: 0.7, quantity: 6 }], xpReward: 1750, currencyReward: 1550, type: 'abomination', weaknesses: ['fire', 'ice', 'thunder'], resistances: ['physical', 'poison'] },
    { id: 'fallen_god', name: '💔 Fallen God', description: 'A god that failed. Its divine power curdled into something terrible.', level: 19, stats: { strength: 22, agility: 16, endurance: 20, intelligence: 24, mana: 130 }, gauges: { hp: 700, maxHp: 700, mp: 200, maxMp: 200 }, abilities: [{ name: 'Divine Wrath', description: 'Broken divine fury', damage: 76, type: 'magical' }, { name: 'Despair', description: 'Godly despair', damage: 66, type: 'mental', statusEffect: 'despair' }], loot: [{ itemId: 'saints_relic', chance: 0.5, quantity: 5 }, { itemId: 'ring_of_memories', chance: 0.1, quantity: 1 }], xpReward: 1850, currencyReward: 1650, type: 'demon', weaknesses: ['void'], resistances: ['holy', 'light'] },

    // ═══ LEVEL 20 ═══
    { id: 'system_avatar', name: '💻 System Avatar', description: 'The System itself — given form. It watches you with cold curiosity.', level: 20, stats: { strength: 25, agility: 20, endurance: 25, intelligence: 30, mana: 200 }, gauges: { hp: 1000, maxHp: 1000, mp: 300, maxMp: 300 }, abilities: [{ name: 'System Error', description: 'Reality glitches', damage: 90, type: 'corruption' }, { name: 'Reset', description: 'Tries to delete you', damage: 100, type: 'corruption' }, { name: 'Observation', description: 'Studies your weakness', damage: 60, type: 'mental' }], loot: [{ itemId: 'phoenix_feather', chance: 0.3, quantity: 3 }, { itemId: 'tower_key_fragment', chance: 0.5, quantity: 5 }, { itemId: 'ring_of_memories', chance: 0.15, quantity: 1 }], xpReward: 2500, currencyReward: 3000, type: 'abomination', weaknesses: ['void'], resistances: ['physical', 'magical', 'mental'] },
    { id: 'doomsday_dragon', name: '🌋 Doomsday Dragon', description: 'The dragon prophesied to end the era. Its awakening shakes the world.', level: 20, stats: { strength: 30, agility: 18, endurance: 28, intelligence: 22, mana: 150 }, gauges: { hp: 1200, maxHp: 1200, mp: 200, maxMp: 200 }, abilities: [{ name: 'Extinction Breath', description: 'Erases all', damage: 95, type: 'magical', statusEffect: 'burning' }, { name: 'Apocalypse Roar', description: 'Shatters worlds', damage: 80, type: 'mental' }], loot: [{ itemId: 'dragons_scale', chance: 0.95, quantity: 10 }, { itemId: 'phoenix_feather', chance: 0.4, quantity: 3 }], xpReward: 2400, currencyReward: 2800, type: 'dragon', weaknesses: ['ice', 'holy'], resistances: ['fire', 'physical', 'shadow'] },
    { id: 'void_sovereign', name: '🌌 Void Sovereign', description: 'The ruler of the void between worlds. Your existence offends it.', level: 20, stats: { strength: 22, agility: 22, endurance: 22, intelligence: 30, mana: 250 }, gauges: { hp: 950, maxHp: 950, mp: 350, maxMp: 350 }, abilities: [{ name: 'Oblivion', description: 'Absolute erasure', damage: 100, type: 'corruption' }, { name: 'Void Storm', description: 'Storm of nothing', damage: 85, type: 'corruption' }, { name: 'Existential Dread', description: 'Makes you doubt reality', damage: 70, type: 'mental', statusEffect: 'madness' }], loot: [{ itemId: 'void_shard', chance: 1.0, quantity: 15 }, { itemId: 'demonic_contract', chance: 0.5, quantity: 3 }, { itemId: 'ring_of_memories', chance: 0.2, quantity: 1 }], xpReward: 2600, currencyReward: 3200, type: 'demon', weaknesses: ['holy', 'light'], resistances: ['void', 'shadow', 'mental', 'physical'] },
]

// Helper to find enemy by name (case/space insensitive)
export function findEnemyByNameOrId(query: string): Enemy | undefined {
    const q = query.toLowerCase().replace(/[^a-z0-9]/g, '')
    return ENEMIES.find(e => {
        const id = e.id.replace(/_/g, '').toLowerCase()
        const name = e.name.replace(/[^a-zA-Z0-9]/g, '').toLowerCase()
        return id === q || name === q || e.id === query
    })
}