import { ItemDefinition, ItemId } from '../types.js'

export const ITEMS: Record<ItemId, ItemDefinition> = {
    rusty_sword: {
        id: 'rusty_sword',
        name: '🗡️ Rusty Sword',
        description: 'A blade that has seen better days. It still cuts.',
        type: 'weapon',
        rarity: 'common',
        lore: 'Standard-issue militia sword. Mass-produced before the System Era.',
        stackable: false,
        corrupt: false,
        corruptRisk: 0,
        evolveable: false,
        bindOnEquip: false,
        equippable: true,
        slot: 'weapon',
        stats: { strength: 2 },
        value: 10
    },
    survivors_knife: {
        id: 'survivors_knife',
        name: "🔪 Survivor's Knife",
        description: 'Small, reliable, and easily hidden. Has saved more lives than any legendary blade.',
        type: 'weapon',
        rarity: 'uncommon',
        lore: 'The first weapon most survivors acquire. Simple but effective.',
        stackable: false,
        corrupt: false,
        corruptRisk: 0,
        evolveable: true,
        evolveTarget: 'cursed_blade_hunger',
        bindOnEquip: true,
        equippable: true,
        slot: 'weapon',
        stats: { strength: 1, agility: 2 },
        effects: ['+10% crit chance vs beasts'],
        value: 35
    },
    cursed_blade_hunger: {
        id: 'cursed_blade_hunger',
        name: '🖤 Cursed Blade: Hunger',
        description: 'A blade that feeds on fear. It whispers in the dark.',
        type: 'weapon',
        rarity: 'cursed',
        lore: 'Forged in the blood of a thousand sacrifices. Every kill makes it stronger.',
        stackable: false,
        corrupt: true,
        corruptRisk: 15,
        evolveable: false,
        bindOnEquip: true,
        equippable: true,
        slot: 'weapon',
        stats: { strength: 8, agility: 3 },
        effects: ['Heals 10% of damage dealt', 'Corruption +2 per kill', 'Whispers reveal hidden truths'],
        value: 0
    },
    shadow_cloak: {
        id: 'shadow_cloak',
        name: '🌑 Shadow Cloak',
        description: 'Woven from captured shadows. Makes you harder to notice — and harder to remember.',
        type: 'armor',
        rarity: 'rare',
        lore: 'Tailored by the Shadow Guild before they vanished. Only eleven were ever made.',
        stackable: false,
        corrupt: true,
        corruptRisk: 5,
        evolveable: false,
        bindOnEquip: true,
        equippable: true,
        slot: 'body',
        stats: { agility: 5 },
        effects: ['15% dodge chance', 'Ambush events favor you', 'NPCs may forget meeting you'],
        value: 500
    },
    ring_of_memories: {
        id: 'ring_of_memories',
        name: '💍 Ring of Memories',
        description: 'A plain silver band that remembers its previous owners. All twelve of them.',
        type: 'accessory',
        rarity: 'legendary',
        lore: 'Each owner left an imprint: births, deaths, betrayals, one regicide.',
        stackable: false,
        corrupt: true,
        corruptRisk: 8,
        evolveable: false,
        bindOnEquip: true,
        equippable: true,
        slot: 'accessory1',
        stats: { intelligence: 6, mana: 4 },
        effects: ['Reveals hidden event choices', '+15% XP gain'],
        value: 2000
    },
    mask_of_madness: {
        id: 'mask_of_madness',
        name: '🎭 Mask of Madness',
        description: 'A beautiful porcelain mask that increases charisma — but slowly eats your sanity.',
        type: 'accessory',
        rarity: 'cursed',
        lore: 'Carved by a playwright driven mad by his own masterpiece.',
        stackable: false,
        corrupt: true,
        corruptRisk: 20,
        evolveable: false,
        bindOnEquip: true,
        equippable: true,
        slot: 'head',
        stats: { intelligence: 5 },
        effects: ['Charisma events always succeed', 'Sanity -3 per event', 'NPCs drawn to you irresistibly'],
        value: 800
    },
    broken_amulet: {
        id: 'broken_amulet',
        name: '🧿 Broken Amulet',
        description: 'Half an amulet. The other half is... somewhere. Both halves still resonate.',
        type: 'accessory',
        rarity: 'uncommon',
        lore: 'Split during a battle between constellations.',
        stackable: false,
        corrupt: false,
        corruptRisk: 0,
        evolveable: true,
        bindOnEquip: false,
        equippable: true,
        slot: 'accessory2',
        stats: { mana: 2 },
        effects: ['Resonates near the other half'],
        value: 0
    },
    phoenix_feather: {
        id: 'phoenix_feather',
        name: '🔥 Phoenix Feather',
        description: 'Still warm. Pulses with a faint heartbeat.',
        type: 'consumable',
        rarity: 'legendary',
        lore: 'Plucked from a dying phoenix. It chose to give it to you.',
        stackable: false,
        corrupt: false,
        corruptRisk: 0,
        evolveable: false,
        bindOnEquip: false,
        equippable: false,
        effects: ['Auto-revives upon death once'],
        value: 5000
    },
    void_shard: {
        id: 'void_shard',
        name: '💠 Void Shard',
        description: 'A crystallized piece of the void between worlds. It hums at a frequency that hurts.',
        type: 'material',
        rarity: 'rare',
        lore: 'Every shard is a piece of something erased from existence.',
        stackable: true,
        corrupt: true,
        corruptRisk: 10,
        evolveable: false,
        bindOnEquip: false,
        equippable: false,
        value: 300
    },
    dragons_scale: {
        id: 'dragons_scale',
        name: "🐉 Dragon's Scale",
        description: 'A single scale from a true dragon. Impervious to most elements.',
        type: 'material',
        rarity: 'legendary',
        lore: 'Dragons shed one scale per century. Each contains a memory fragment.',
        stackable: true,
        corrupt: false,
        corruptRisk: 0,
        evolveable: false,
        bindOnEquip: false,
        equippable: false,
        effects: ['Dragon resistance +10% in inventory'],
        value: 1500
    },
    blood_crystal: {
        id: 'blood_crystal',
        name: '🩸 Blood Crystal',
        description: 'Crystallized blood from an ancient entity. Warm to the touch.',
        type: 'material',
        rarity: 'uncommon',
        corrupt: true,
        corruptRisk: 5,
        evolveable: false,
        bindOnEquip: false,
        equippable: false,
        stackable: true,
        lore: 'Blood that should have faded centuries ago.',
        effects: ['Blood affinity +5 XP'],
        value: 150
    },
    saints_relic: {
        id: 'saints_relic',
        name: "✝️ Saint's Relic",
        description: 'A finger bone of a forgotten saint. Still radiates faint holy energy.',
        type: 'accessory',
        rarity: 'rare',
        lore: 'The saint was canonized after death. The truth is more complicated.',
        stackable: false,
        corrupt: false,
        corruptRisk: 0,
        evolveable: false,
        bindOnEquip: true,
        equippable: true,
        slot: 'accessory1',
        stats: { mana: 4, endurance: 2 },
        effects: ['Holy damage +15%', 'Undead fear you'],
        value: 900
    },
    expired_ration: {
        id: 'expired_ration',
        name: '🥫 Expired Ration',
        description: 'Probably still edible. Probably.',
        type: 'consumable',
        rarity: 'junk',
        lore: 'Pre-System military rations. Nobody knows what is in them.',
        stackable: true,
        corrupt: false,
        corruptRisk: 0,
        evolveable: false,
        bindOnEquip: false,
        equippable: false,
        effects: ['Restores 15 HP', 'Small chance of -5 HP'],
        value: 3
    },
    mana_potion_small: {
        id: 'mana_potion_small',
        name: '💙 Mana Potion (Small)',
        description: 'A small vial of shimmering blue liquid. Restores mana.',
        type: 'consumable',
        rarity: 'common',
        lore: 'Brewed using basic alchemy. Most apothecaries can make them.',
        stackable: true,
        corrupt: false,
        corruptRisk: 0,
        evolveable: false,
        bindOnEquip: false,
        equippable: false,
        effects: ['Restores 30 MP'],
        value: 15
    },
    bandage: {
        id: 'bandage',
        name: '🩹 Bandage',
        description: 'Clean bandages. Harder to find than you would expect.',
        type: 'consumable',
        rarity: 'common',
        lore: 'Medical supplies became scarce after the first week.',
        stackable: true,
        corrupt: false,
        corruptRisk: 0,
        evolveable: false,
        bindOnEquip: false,
        equippable: false,
        effects: ['Restores 25 HP'],
        value: 10
    },
    demonic_contract: {
        id: 'demonic_contract',
        name: '📜 Demonic Contract',
        description: 'A parchment that burns cold. Your soul may be at risk.',
        type: 'key_item',
        rarity: 'cursed',
        lore: 'Every demonic contract has a loophole. Find it before the due date.',
        stackable: false,
        corrupt: true,
        corruptRisk: 0,
        evolveable: false,
        bindOnEquip: false,
        equippable: false,
        effects: ['Opens special event chain', 'Powerful boon with hidden cost'],
        value: 0
    },
    holy_water: {
        id: 'holy_water',
        name: '💧 Holy Water',
        description: 'Blessed by a priest who has since died. His faith lingers.',
        type: 'consumable',
        rarity: 'uncommon',
        lore: 'Blessed in the Third Cathedral, three days before it fell.',
        stackable: true,
        corrupt: false,
        corruptRisk: 0,
        evolveable: false,
        bindOnEquip: false,
        equippable: false,
        effects: ['Cleanses minor corruption', '40 damage to undead/demons'],
        value: 50
    },
    black_market_key: {
        id: 'black_market_key',
        name: '🔑 Black Market Key',
        description: "A key that opens doors that officially don't exist.",
        type: 'key_item',
        rarity: 'rare',
        lore: 'The Black Market exists in every city that still stands.',
        stackable: false,
        corrupt: false,
        corruptRisk: 0,
        evolveable: false,
        bindOnEquip: false,
        equippable: false,
        effects: ['Black market access', 'Special items available'],
        value: 500
    },
    tower_key_fragment: {
        id: 'tower_key_fragment',
        name: '🗼 Tower Key Fragment',
        description: 'One piece of a key to a Tower. Three more needed.',
        type: 'key_item',
        rarity: 'rare',
        lore: 'The Towers appeared overnight. Their keys were scattered.',
        stackable: false,
        corrupt: false,
        corruptRisk: 0,
        evolveable: false,
        bindOnEquip: false,
        equippable: false,
        effects: ['1/4 Tower Key. Towers contain challenges and rewards.'],
        value: 0
    },
    memory_shard: {
        id: 'memory_shard',
        name: '💎 Memory Shard',
        description: 'A crystallized memory from someone who died before the System.',
        type: 'consumable',
        rarity: 'rare',
        lore: 'Some memories were too powerful to fade. They crystallized instead.',
        stackable: true,
        corrupt: false,
        corruptRisk: 0,
        evolveable: false,
        bindOnEquip: false,
        equippable: false,
        effects: ['Gain XP', 'May reveal hidden lore', 'Chance: timeline fragment'],
        value: 200
    }
}

export type { ItemId, ItemDefinition }