import { Zone, ZoneId } from '../types.js'

export const ZONES: Record<ZoneId, Zone> = {
    survivor_camp: {
        id: 'survivor_camp',
        name: '🏕️ Survivor Camp',
        description: 'A makeshift settlement of desperate survivors. Resources are scarce but hope lingers.',
        icon: '🏕️',
        x: 400, y: 320,
        connections: ['ruined_city', 'dark_forest'],
        minLevel: 1,
        enemies: ['starving_wolf'],
        events: ['starving_child', 'strange_merchant'],
        treasureMultiplier: 0.5,
        dangerLevel: 1,
        lore: 'The first gathering point for those who survived the System descent. The camp leader is a former firefighter named Marcus.'
    },
    ruined_city: {
        id: 'ruined_city',
        name: '🏚️ Ruined City',
        description: 'Once a thriving metropolis. Now shattered buildings and hollow streets echo with distant screams.',
        icon: '🏚️',
        x: 520, y: 260,
        connections: ['survivor_camp', 'cathedral_ruins', 'black_market_district', 'scorched_plains'],
        minLevel: 2,
        enemies: ['undead_soldier', 'corrupted_goblin'],
        events: ['burning_building', 'starving_child'],
        treasureMultiplier: 1.0,
        dangerLevel: 3,
        lore: 'District 7 fell first. The Cathedral held for three days. The bells rang three times before silence.'
    },
    dark_forest: {
        id: 'dark_forest',
        name: '🌲 Dark Forest',
        description: 'An ancient forest twisted by the System. Trees whisper secrets. Shadows move on their own.',
        icon: '🌲',
        x: 280, y: 400,
        connections: ['survivor_camp', 'scorched_plains', 'frozen_wastes'],
        minLevel: 3,
        enemies: ['shadow_stalker', 'blood_disciple'],
        events: ['strange_merchant'],
        treasureMultiplier: 1.3,
        dangerLevel: 4,
        lore: 'The forest was here before the System. Some say it welcomed the change. The deeper you go, the stranger it gets.'
    },
    scorched_plains: {
        id: 'scorched_plains',
        name: '🔥 Scorched Plains',
        description: 'A vast wasteland burned clean by dragon fire. Nothing grows here, but treasures lie buried in ash.',
        icon: '🔥',
        x: 560, y: 380,
        connections: ['ruined_city', 'dark_forest', 'tower_gate'],
        minLevel: 5,
        requiredTraits: ['iron_will'],
        enemies: ['fallen_knight', 'blood_disciple'],
        events: ['survivor_camp_attack'],
        treasureMultiplier: 1.5,
        dangerLevel: 5,
        lore: 'The Young Drake first appeared here. It burned three cities before retreating. The ashes are still warm.'
    },
    cathedral_ruins: {
        id: 'cathedral_ruins',
        name: '⛪ Cathedral Ruins',
        description: 'The holy ground where a saint fell. The air still hums with dying prayers.',
        icon: '⛪',
        x: 600, y: 180,
        connections: ['ruined_city', 'tower_gate'],
        minLevel: 6,
        enemies: ['fallen_knight', 'void_herald'],
        events: ['first_awakening'],
        treasureMultiplier: 1.8,
        dangerLevel: 6,
        lore: 'When the bells rang three times, the saint stood alone against the void. She fell. But she took something with her.'
    },
    black_market_district: {
        id: 'black_market_district',
        name: '🏴 Black Market District',
        description: 'Hidden beneath the ruins, a thriving black market runs on secrets and stolen goods.',
        icon: '🏴',
        x: 680, y: 310,
        connections: ['ruined_city'],
        minLevel: 4,
        enemies: ['blood_disciple'],
        events: ['strange_merchant'],
        treasureMultiplier: 2.0,
        dangerLevel: 3,
        lore: 'Run by the Shadow Guild. Everything has a price here — including lives. The Void Merchant visits every third night.'
    },
    tower_gate: {
        id: 'tower_gate',
        name: '🗼 Tower Gate',
        description: 'The entrance to a Tower. Immense power awaits those who dare climb. Most never return.',
        icon: '🗼',
        x: 720, y: 200,
        connections: ['cathedral_ruins', 'scorched_plains', 'void_rift'],
        minLevel: 8,
        requiredTitles: ['goblin_executioner'],
        enemies: ['young_drake', 'void_herald'],
        events: [],
        treasureMultiplier: 3.0,
        dangerLevel: 8,
        lore: 'No one knows who built the Towers. The first climber reached Floor 50 before vanishing. Their name is still whispered.'
    },
    frozen_wastes: {
        id: 'frozen_wastes',
        name: '❄️ Frozen Wastes',
        description: 'An endless frozen tundra. The cold seeps into your soul. Something ancient sleeps beneath the ice.',
        icon: '❄️',
        x: 160, y: 220,
        connections: ['dark_forest', 'void_rift'],
        minLevel: 7,
        enemies: ['shadow_stalker', 'young_drake'],
        events: ['survivor_camp_attack'],
        treasureMultiplier: 1.6,
        dangerLevel: 7,
        lore: 'The ice predates the System. Carvings in ancient languages suggest something was sealed here long before the world ended.'
    },
    void_rift: {
        id: 'void_rift',
        name: '🌌 Void Rift',
        description: 'A tear in reality where the void bleeds into the world. Only the mad or the blessed can survive here.',
        icon: '🌌',
        x: 400, y: 120,
        connections: ['tower_gate', 'frozen_wastes', 'abyssal_depths'],
        minLevel: 9,
        requiredTraits: ['void_touched'],
        enemies: ['void_herald'],
        events: [],
        treasureMultiplier: 4.0,
        dangerLevel: 9,
        lore: 'The rift appeared on Day 13. It has been growing ever since. The Brainship says it will consume the continent within the year.'
    },
    abyssal_depths: {
        id: 'abyssal_depths',
        name: '🕳️ Abyssal Depths',
        description: 'Below the void, deeper than light can reach. The source of the corruption. The end of all things.',
        icon: '🕳️',
        x: 400, y: 30,
        connections: ['void_rift'],
        minLevel: 12,
        requiredEvolution: 'void_path',
        enemies: ['void_herald', 'young_drake'],
        events: [],
        treasureMultiplier: 5.0,
        dangerLevel: 10,
        lore: 'None who entered have returned. But sometimes, at midnight, you can hear them screaming from below.'
    }
}