module.exports = {
  reconnect: {
    baseDelayMs: 3_000,
    maxDelayMs: 30_000,
  },
  access: {
    states: ["none", "allowed", "trusted"],
  },
  commands: {
    defaultCooldownSeconds: 3,
  },
  scheduler: {
    tickIntervalMs: 30_000,
    vuSyncIntervalMs: 15 * 60 * 1000,
  },
  groups: {
    welcomeTemplate:
      "*@{{name}}* welcome to *{{group}}*.\n\n{{description}}",
    farewellTemplate:
      "@{{name}} left *{{group}}*.",
  },
  media: {
    maxStickerVideoSeconds: 10,
  },
xp: {
    dailyMin: 25,
    dailyMax: 50,
    commandMin: 3,
    commandMax: 8,
    gameMaxDaily: 100,
    roles: ["Scholar", "Coder", "Strategist", "Sprinter", "Night Owl"],
  },
economy: {
    dailyCashMin: 50,
    dailyCashMax: 100,
    begCooldownMs: 10 * 60 * 1000,
    begMin: 10,
    begMax: 30,
    workCooldownMs: 45 * 60 * 1000,
    workMin: 40,
    workMax: 80,
    fishCooldownMs: 20 * 60 * 1000,
    fishMin: 60,
    fishMax: 140,
    fishMissRate: 0.18,
    mineCooldownMs: 25 * 60 * 1000,
    mineMin: 70,
    mineMax: 160,
    mineMissRate: 0.2,
    huntCooldownMs: 30 * 60 * 1000,
    huntMin: 70,
    huntMax: 160,
    huntMissRate: 0.22,
    farmCooldownMs: 75 * 60 * 1000,
    farmMin: 120,
    farmMax: 220,
    investCooldownMs: 90 * 60 * 1000,
    investMinAmount: 100,
    investDurationMs: 90 * 60 * 1000,
    investLossRate: 0.15,
    investMinMultiplier: 0.85,
    investMaxMultiplier: 1.35,
    collectCooldownMs: 5 * 60 * 1000,
    crimeCooldownMs: 60 * 60 * 1000,
    crimeSuccessRate: 0.35,
    crimeSuccessMin: 60,
    crimeSuccessMax: 150,
    crimeFailMin: 20,
    crimeFailMax: 60,
    robCooldownMs: 2 * 60 * 60 * 1000,
    robSuccessRate: 0.35,
    robMinTargetWallet: 80,
    robMinSteal: 40,
    robMaxSteal: 150,
    robFailMin: 30,
    robFailMax: 80,
    duelCooldownMs: 25 * 60 * 1000,
    duelMinBet: 50,
    duelMaxBet: 5_000,
    heistCooldownMs: 4 * 60 * 60 * 1000,
    heistSuccessRate: 0.28,
    heistMinTargetBank: 350,
    heistMinSteal: 100,
    heistMaxSteal: 300,
    heistFailMin: 60,
    heistFailMax: 150,
    coinflipMinBet: 25,
    coinflipMaxBet: 5_000,
    diceMinBet: 25,
    diceMaxBet: 5_000,
    blackjackMinBet: 50,
    blackjackMaxBet: 7_500,
    rouletteMinBet: 25,
    rouletteMaxBet: 7_500,
gameRewards: {
      daily: { xpLabel: true },
      math: { xp: 15, cash: 30 },
      guess: { xp: 18, cash: 40 },
      trivia: { xp: 20, cash: 50 },
      rps: {
        win: { xp: 12, cash: 30 },
        draw: { xp: 5, cash: 10 },
        lose: { xp: 1, cash: 2 },
      },
      slot: {
        jackpot: { xp: 30, cash: 80 },
        pair: { xp: 10, cash: 25 },
        miss: { xp: 0, cash: 0 },
      },
    },
    jobs: [
      {
        key: "courier",
        name: "Courier",
        description: "Fast feet, steady tips, and efficient shift bonuses.",
        modifiers: {
          reward: { beg: 0.1, work: 0.16 },
          cooldown: { beg: -0.1, work: -0.08 },
        },
      },
      {
        key: "angler",
        name: "Angler",
        description: "Knows the waters and pulls bigger catches from the deep.",
        modifiers: {
          reward: { fish: 0.26 },
          cooldown: { fish: -0.18 },
          success: { fish: 0.08 },
        },
      },
      {
        key: "miner",
        name: "Miner",
        description: "Excels at digging up rarer ore and bigger payout veins.",
        modifiers: {
          reward: { mine: 0.26 },
          cooldown: { mine: -0.16 },
          success: { mine: 0.08 },
        },
      },
      {
        key: "hunter",
        name: "Hunter",
        description: "Tracks prey more efficiently and rarely returns empty-handed.",
        modifiers: {
          reward: { hunt: 0.24 },
          cooldown: { hunt: -0.12 },
          success: { hunt: 0.1 },
        },
      },
      {
        key: "broker",
        name: "Broker",
        description: "Plays the long game with investment boosts and sharper returns.",
        modifiers: {
          payout: { invest: 0.18 },
          reward: { collect: 0.08 },
        },
      },
      {
        key: "outlaw",
        name: "Outlaw",
        description: "Lives dangerously with better odds in risky money plays.",
        modifiers: {
          success: { crime: 0.08, rob: 0.06, heist: 0.05, duel: 0.03 },
          reward: { crime: 0.12, rob: 0.08, heist: 0.12 },
        },
      },
    ],
    factions: [
      {
        key: "ember-claw",
        name: "Ember Claw",
        description: "Aggressive earners who thrive in crime, duels, and pressure plays.",
        bonusProfile: {
          reward: { crime: 0.1, duel: 0.06, heist: 0.08 },
          success: { crime: 0.05, heist: 0.04 },
        },
      },
      {
        key: "azure-tide",
        name: "Azure Tide",
        description: "Fluid gatherers with a gift for fishing, hunting, and fast recoveries.",
        bonusProfile: {
          reward: { fish: 0.12, hunt: 0.1 },
          cooldown: { fish: -0.08, hunt: -0.06 },
        },
      },
      {
        key: "verdant-bloom",
        name: "Verdant Bloom",
        description: "Patient growers who profit from farming, collecting, and long sessions.",
        bonusProfile: {
          reward: { farm: 0.14, collect: 0.08 },
          payout: { invest: 0.08 },
        },
      },
      {
        key: "vault-syndicate",
        name: "Vault Syndicate",
        description: "Bank-minded strategists who turn clean money into bigger returns.",
        bonusProfile: {
          reward: { work: 0.08 },
          payout: { invest: 0.14 },
          bank: { wealth: 0.04 },
        },
      },
    ],
    shopItems: [
      {
        key: "bamboo_rod",
        name: "Bamboo Rod",
        price: 260,
        type: "tool",
        slot: "tool",
        activity: "fish",
        description: "A starter fishing rod that smooths out bad casts.",
        modifiers: {
          reward: { fish: 0.12 },
          success: { fish: 0.05 },
        },
      },
      {
        key: "iron_pickaxe",
        name: "Iron Pickaxe",
        price: 420,
        type: "tool",
        slot: "tool",
        activity: "mine",
        description: "A weighty pickaxe that turns rough shifts into richer hauls.",
        modifiers: {
          reward: { mine: 0.14 },
          success: { mine: 0.06 },
        },
      },
      {
        key: "tracking_kit",
        name: "Tracking Kit",
        price: 460,
        type: "tool",
        slot: "tool",
        activity: "hunt",
        description: "A premium field pack that makes hunts more reliable.",
        modifiers: {
          reward: { hunt: 0.13 },
          success: { hunt: 0.07 },
        },
      },
      {
        key: "seed_satchel",
        name: "Seed Satchel",
        price: 380,
        type: "tool",
        slot: "tool",
        activity: "farm",
        description: "Special seeds that help crops come in thicker and richer.",
        modifiers: {
          reward: { farm: 0.15 },
        },
      },
      {
        key: "lucky_dango",
        name: "Lucky Dango",
        price: 210,
        type: "consumable",
        durationMs: 60 * 60 * 1000,
        description: "A sweet boost that sharpens your luck in risky commands.",
        modifiers: {
          success: { crime: 0.06, rob: 0.04, heist: 0.04, coinflip: 0.02 },
        },
      },
      {
        key: "focus_scroll",
        name: "Focus Scroll",
        price: 240,
        type: "consumable",
        durationMs: 60 * 60 * 1000,
        description: "Cuts downtime and helps gather-focused jobs cash out faster.",
        modifiers: {
          cooldown: { fish: -0.12, mine: -0.12, hunt: -0.1, work: -0.08 },
        },
      },
      {
        key: "bank_pass",
        name: "Bank Pass",
        price: 320,
        type: "consumable",
        durationMs: 2 * 60 * 60 * 1000,
        description: "Improves investment collection and calm-money plays.",
        modifiers: {
          payout: { invest: 0.12 },
        },
      },
      {
        key: "neon_badge",
        name: "Neon Badge",
        price: 900,
        type: "cosmetic",
        description: "Pure status. Stylish flex with no gameplay effect.",
      },
      {
        key: "golden_ticket",
        name: "Golden Ticket",
        price: 1350,
        type: "cosmetic",
        description: "Collector-grade luxury for your inventory showcase.",
      },
    ],
  },
};
