import { initAuthCreds, proto } from 'baileys'
import SessionCredsModel from './Mongo/Models/SessionCreds.js'
import SessionKeyModel from './Mongo/Models/SessionKey.js'
import { BufferJSON } from '../utils/buffer-json.js'
import { decryptString, encryptString } from '../utils/secure-store.js'

let authPersistCount = 0
let authPersistDuration = 0
let authKeyWriteCount = 0
let authKeyFetchDuration = 0
let sessionRestoreCount = 0
let qrRequiredCount = 0
let reconnectCount = 0

let categoryWriteCount: Record<string, number> = {}
let categoryKeyCount: Record<string, number> = {}
let appStateSyncWrites = 0
let appStateVersionWrites = 0
let senderKeyWrites = 0
let sessionWrites = 0

let encryptionKeyMismatchWarnings = 0
let encryptionKeyAutoGenerated = false

let orphanPreKeys = 0
let orphanSenderKeys = 0
let orphanSessions = 0

let authIntegrityMetrics = {
    sessionId: '',
    credsLoaded: false,
    keysLoaded: 0,
    keysWritten: 0,
    bulkWriteDuration: 0,
    keyFetchDuration: 0,
    reconnectCount: 0,
    sessionRestoreSuccess: false,
    qrRequired: false
}

export function getAuthMetrics() {
    return {
        persistCount: authPersistCount,
        totalDuration: authPersistDuration,
        keysWritten: authKeyWriteCount,
        keyFetchDuration: authKeyFetchDuration,
        sessionRestoreCount,
        qrRequiredCount,
        reconnectCount,
        categoryWriteCount: { ...categoryWriteCount },
        categoryKeyCount: { ...categoryKeyCount },
        appStateSyncWrites,
        appStateVersionWrites,
        senderKeyWrites,
        sessionWrites,
        encryptionKeyMismatchWarnings,
        encryptionKeyAutoGenerated,
        integrity: { ...authIntegrityMetrics }
    }
}

export function resetAuthMetrics() {
    authPersistCount = 0
    authPersistDuration = 0
    authKeyWriteCount = 0
    authKeyFetchDuration = 0
    sessionRestoreCount = 0
    qrRequiredCount = 0
    reconnectCount = 0
    categoryWriteCount = {}
    categoryKeyCount = {}
    appStateSyncWrites = 0
    appStateVersionWrites = 0
    senderKeyWrites = 0
    sessionWrites = 0
    encryptionKeyMismatchWarnings = 0
    authIntegrityMetrics = {
        sessionId: '',
        credsLoaded: false,
        keysLoaded: 0,
        keysWritten: 0,
        bulkWriteDuration: 0,
        keyFetchDuration: 0,
        reconnectCount: 0,
        sessionRestoreSuccess: false,
        qrRequired: false
    }
}

export class MongoAuthStore {
    private sessionId: string
    private logger: { warn: (obj: object, msg: string) => void; info?: (obj: object, msg: string) => void }
    private encryptionKey: string
    private keyMap: Record<string, string> = {
        "pre-key": "preKeys",
        session: "sessions",
        "sender-key": "senderKeys",
        "app-state-sync-key": "appStateSyncKeys",
        "app-state-sync-version": "appStateVersions",
        "sender-key-memory": "senderKeyMemory",
        "device-list": "deviceLists",
        "identity-key": "identityKeys",
        "lid-mapping": "lidMappings",
        tctoken: "tcTokens"
    }
    private reverseKeyMap: Record<string, string>
    private keyCountByCategory: Record<string, number> = {}

    constructor({ sessionId, logger, encryptionKey }: { sessionId: string; logger: { warn: (obj: object, msg: string) => void; info?: (obj: object, msg: string) => void }; encryptionKey: string }) {
        this.sessionId = sessionId
        this.logger = logger
        this.encryptionKey = encryptionKey
        this.reverseKeyMap = Object.fromEntries(Object.entries(this.keyMap).map(([type, key]) => [key, type]))
    }

    async loadCredsDocument() {
        const document = await SessionCredsModel.findOneAndUpdate(
            { sessionId: this.sessionId },
            { $setOnInsert: { sessionId: this.sessionId, encryptionKey: this.encryptionKey } },
            { upsert: true, new: true, setDefaultsOnInsert: true }
        )
        return document
    }

    async getAuthState() {
        const document = await this.loadCredsDocument()
        let creds = initAuthCreds()
        let legacySessionDetected = false
        let keysLoaded = 0
        let credsLoaded = false

        authIntegrityMetrics.sessionId = this.sessionId

        if (document && (document as { encryptionKey?: string }).encryptionKey) {
            const storedKey = (document as { encryptionKey: string }).encryptionKey
            if (storedKey && storedKey !== this.encryptionKey) {
                this.logger.warn({}, `Encryption key mismatch — using stored key for session`)
                encryptionKeyMismatchWarnings++
            }
        }

        const credsPayload = (document as { creds?: string })?.creds
        if (credsPayload) {
            try {
                creds = JSON.parse(decryptString(credsPayload, this.encryptionKey), BufferJSON.reviver)
                credsLoaded = true
                authIntegrityMetrics.credsLoaded = true
            } catch (error) {
                this.logger.warn({ error }, "Failed to parse stored WhatsApp creds")
            }
        }

        const categories = Object.values(this.keyMap)
        for (const category of categories) {
            const count = await SessionKeyModel.countDocuments({
                sessionId: this.sessionId,
                category
            }).lean().exec()
            if (count > 0) {
                this.keyCountByCategory[category] = count
                keysLoaded += count
            }
        }
        authIntegrityMetrics.keysLoaded = keysLoaded
        sessionRestoreCount++
        authIntegrityMetrics.sessionRestoreSuccess = true

        if (!credsLoaded) {
            qrRequiredCount++
            authIntegrityMetrics.qrRequired = true
        }

        if (this.logger.info) {
            this.logger.info({
                sessionId: this.sessionId,
                credsLoaded,
                keysLoaded,
                keyCounts: { ...this.keyCountByCategory }
            }, `[AUTH_INTEGRITY] sessionId= credsLoaded= keysLoaded= keyCounts=`)
        }

        this.checkRailwaySafety()

        const keyStore = {
            get: async (type: string, ids: string[]) => {
                const storeKey = this.keyMap[type] || type
                const result: Record<string, unknown> = {}

                if (!ids || ids.length === 0) return result

                const fetchStart = Date.now()
                const records = await SessionKeyModel.find({
                    sessionId: this.sessionId,
                    category: storeKey,
                    keyId: { $in: ids }
                }).lean().exec()
                const fetchDuration = Date.now() - fetchStart
                authKeyFetchDuration += fetchDuration
                authIntegrityMetrics.keyFetchDuration = fetchDuration

                for (const record of records as { keyId: string; value: string }[]) {
                    const value = this.deserializeKeyValue(record.value, type)
                    result[record.keyId] = value
                }

                return result
            },
            set: async (data: Record<string, Record<string, unknown>>) => {
                const bulkOps: { updateOne: { filter: object; update: object; upsert: boolean } }[] = []
                let keysWrittenThisBatch = 0

                for (const [type, values] of Object.entries(data || {})) {
                    const storeKey = this.keyMap[type] || type
                    const category = storeKey

                    categoryWriteCount[category] = (categoryWriteCount[category] || 0) + Object.keys(values || {}).length

                    if (type === "app-state-sync-key") appStateSyncWrites++
                    if (type === "app-state-sync-version") appStateVersionWrites++
                    if (type === "sender-key") senderKeyWrites++
                    if (type === "session") sessionWrites++

                    for (const [id, value] of Object.entries(values || {})) {
                        if (value === null || typeof value === "undefined") {
                            bulkOps.push({
                                updateOne: {
                                    filter: { sessionId: this.sessionId, category, keyId: id },
                                    update: { $set: { sessionId: this.sessionId, category, keyId: id, value: "", encryptionKey: this.encryptionKey } },
                                    upsert: true
                                }
                            })
                        } else {
                            const serialized = JSON.stringify(value, BufferJSON.replacer, 2)
                            const encrypted = encryptString(serialized, this.encryptionKey)
                            bulkOps.push({
                                updateOne: {
                                    filter: { sessionId: this.sessionId, category, keyId: id },
                                    update: { $set: { sessionId: this.sessionId, category, keyId: id, value: encrypted, encryptionKey: this.encryptionKey } },
                                    upsert: true
                                }
                            })
                        }
                        keysWrittenThisBatch++
                    }
                }

                if (bulkOps.length > 0) {
                    const bulkStart = Date.now()
                    await SessionKeyModel.bulkWrite(bulkOps, { ordered: true })
                    const bulkDuration = Date.now() - bulkStart
                    authKeyWriteCount += bulkOps.length
                    authPersistDuration += bulkDuration
                    authIntegrityMetrics.keysWritten = (authIntegrityMetrics.keysWritten || 0) + bulkOps.length
                    authIntegrityMetrics.bulkWriteDuration = bulkDuration

                    if (this.logger.info) {
                        this.logger.info({
                            sessionId: this.sessionId,
                            keysWritten: bulkOps.length,
                            bulkWriteDuration: bulkDuration,
                            keyFetchDuration: authIntegrityMetrics.keyFetchDuration,
                            reconnectCount,
                            sessionRestoreSuccess: authIntegrityMetrics.sessionRestoreSuccess,
                            qrRequired: authIntegrityMetrics.qrRequired
                        }, `[AUTH_INTEGRITY] sessionId= keysWritten= bulkWriteDuration= keyFetchDuration= reconnectCount= sessionRestoreSuccess= qrRequired=`)
                    }
                }
            }
        }

        const saveCreds = async () => {
            const start = Date.now()
            const payload = encryptString(JSON.stringify(creds, BufferJSON.replacer, 2), this.encryptionKey)
            await SessionCredsModel.updateOne(
                { sessionId: this.sessionId },
                { $set: { creds: payload, encryptionKey: this.encryptionKey } }
            )
            authPersistCount++
            authPersistDuration += Date.now() - start
            if (this.logger.info) {
                this.logger.info({ sessionId: this.sessionId, credsSize: payload.length, totalDuration: Date.now() - start }, `[AUTH_STORAGE] sessionId= credsSize= persistDuration=`)
            }
        }

        return {
            state: { creds, keys: keyStore },
            saveCreds,
            legacySessionDetected,
            clear: async () => {
                await Promise.all([
                    SessionCredsModel.deleteOne({ sessionId: this.sessionId }),
                    SessionKeyModel.deleteMany({ sessionId: this.sessionId })
                ])
            }
        }
    }

    private checkRailwaySafety() {
        const envKey = process.env.APP_ENCRYPTION_KEY
        if (!envKey) {
            if (!encryptionKeyAutoGenerated) {
                encryptionKeyAutoGenerated = true
                this.logger.warn({}, `[RAILWAY_SAFETY] APP_ENCRYPTION_KEY not set — key will auto-generate on restart!`)
                this.logger.warn({}, `[RAILWAY_SAFETY] This will cause session loss on ephemeral restarts. Set APP_ENCRYPTION_KEY env var!`)
            }
        }
    }

    async analyzeOrphans(): Promise<{ preKeys: number; senderKeys: number; sessions: number }> {
        const thirtyDaysAgo = new Date(Date.now() - 30 * 24 * 60 * 60 * 1000)
        const oldPreKeys = await SessionKeyModel.countDocuments({
            sessionId: this.sessionId,
            category: "preKeys",
            updatedAt: { $lt: thirtyDaysAgo }
        }).lean().exec()
        orphanPreKeys += oldPreKeys

        return { preKeys: oldPreKeys, senderKeys: orphanSenderKeys, sessions: orphanSessions }
    }

    deserializeKeyValue(value: string, type: string) {
        if (!value) return null
        try {
            let parsed = JSON.parse(decryptString(value, this.encryptionKey), BufferJSON.reviver)
            if (type === "app-state-sync-key" && parsed) {
                const appStateSyncKeyProto = (proto as unknown as { AppStateSyncKeyData?: { fromObject: (v: unknown) => unknown } }).AppStateSyncKeyData || (proto as unknown as { Message?: { AppStateSyncKeyData?: { fromObject: (v: unknown) => unknown } } }).Message?.AppStateSyncKeyData
                if (appStateSyncKeyProto) {
                    parsed = appStateSyncKeyProto.fromObject(parsed)
                }
            }
            return parsed
        } catch (error) {
            this.logger.warn({ error }, "Failed to deserialize key value")
            return null
        }
    }
}

export async function getSessionStorageStats(sessionId?: string) {
    const filter = sessionId ? { sessionId } : {}

    const credsCount = await SessionCredsModel.countDocuments(filter).lean().exec()
    const credsStats = await SessionCredsModel.aggregate([
        { $match: filter },
        { $project: { credsLen: { $strLenBytes: "$creds" } } },
        { $group: { _id: null, avgSize: { $avg: "$credsLen" }, maxSize: { $max: "$credsLen" } } }
    ]).exec()

    const totalKeys = await SessionKeyModel.countDocuments(filter).lean().exec()

    const categoryStats = await SessionKeyModel.aggregate([
        { $match: filter },
        { $group: { _id: { category: "$category" }, count: { $sum: 1 }, avgValueLen: { $avg: { $strLenBytes: "$value" } } } },
        { $sort: { count: -1 } }
    ]).exec()

    return {
        credsCount,
        totalKeys,
        credsAvgSize: credsStats[0]?.avgSize || 0,
        credsMaxSize: credsStats[0]?.maxSize || 0,
        categoryStats: categoryStats.map((c: { _id: { category: string }; count: number; avgValueLen: number }) => ({
            category: c._id.category,
            count: c.count,
            avgValueLen: Math.round(c.avgValueLen || 0)
        }))
    }
}